name = "And Server"
author = "PoolloverNathan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
unsup = "1.0.2"

[options]
no-internal-hashes = true
